FROM nvcr.io/nvidia/pytorch:23.09-py3

RUN pip install transformers==4.39.3

RUN pip install accelerate==0.34.2

RUN pip install datasets==2.18.0

RUN pip install timm==1.0.9

RUN pip install anls==0.0.2

RUN pip install pycocoevalcap==1.2

